##
# MVdWUpdater Plugin
#
# @copyright MVdW Software 2014-2017
# @author Maxim Van de Wynckel (Maximvdw)
##

name: MVdWUpdater
version: 1.5.0
description: SpigotMC MVdW plugin updater
author: Maximvdw
website: http://www.mvdw-software.com/
main: be.maximvdw.mvdwupdater.MVdWUpdater